FROM node:lts-alpine

WORKDIR /app

COPY package.json ./

RUN  npm install

# Copy all app to the Current Working Directory
COPY . .

EXPOSE 1753

CMD ["npm", "run", "dev"]


# docker-composer up # to start the compilation process
# to install npm package run
# docker-compose exec web npm i bootstrap